Guía para desplegar la aplicación.
CraterMaik/myChat pull request #2
Opened 2021-01-04 19:58 UTC by MrTierrin

Para desplegar la aplicación o correrla localmente.

Todo en el [README.md](https://github.com/MrTierrin/myChat/blob/master/README.md)

2021-01-04 20:08 UTC, Awoocado commented on README.md
> +En el archivo `.env.example` que se encuentra en la carpeta principal esta un ejemplo de CraterMaik de como deberia ser el `.env` (Pero mejor leen arriba).
No seria "Pero mejor lean arriba"?

2021-01-04 20:37 UTC, MrTierrin commented on README.md
> +En el archivo `.env.example` que se encuentra en la carpeta principal esta un ejemplo de CraterMaik de como deberia ser el `.env` (Pero mejor leen arriba).
Tal vez, como quieras sirve.

2021-01-05 01:57 UTC, AndreMor955 requested changes

2021-01-05 01:57 UTC, AndreMor955 commented on README.md
> +> NOTA: En producción tal vez quieras ejecutar tu app con nodejs (`node index.js`) desde algun servicio que la mantenga activa, por ejemplo [systemd](https://en.wikipedia.org/wiki/Systemd) (Wikipedia
Nope, lo correcto sería "Administrador de servicios".

2021-01-05 01:57 UTC, AndreMor955 commented on README.md
> +## Instrucciones para publicar a producción
Seria mejor "Instrucciones para desplegar a producción".
Porque también lo puedo hacer privado, y eso no cuenta como publicación.

2021-01-05 17:23 UTC, CraterMaik commented
Good, para empezar

2021-01-05 17:23 UTC, merged